name: wipes_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tqdm
  - pip:
    - submodules/diff-wipes-rasterization
    - submodules/simple-knn